/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Chat;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ChatControllerApi
 */
@Ignore
public class ChatControllerApiTest {

    private final ChatControllerApi api = new ChatControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMessagesTest() throws Exception {
        Object response = api.getMessages();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMessagesByRoomTest() throws Exception {
        String room = null;
        Object response = api.getMessagesByRoom(room);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMessagesCountTest() throws Exception {
        Long response = api.getMessagesCount();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRoomsTest() throws Exception {
        Object response = api.getRooms();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void sendMessagesByRoomTest() throws Exception {
        String sender = null;
        String room = null;
        String message = null;
        Chat response = api.sendMessagesByRoom(sender, room, message);

        // TODO: test validations
    }
}
