/*
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for HelloWorldControllerApi
 */
@Ignore
public class HelloWorldControllerApiTest {

    private final HelloWorldControllerApi api = new HelloWorldControllerApi();

    /**
     * This is a operation code doc.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void helloTest() throws Exception {
        String response = api.hello();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void helloCombindedTest() throws Exception {
        String name = null;
        String greeting = null;
        String response = api.helloCombinded(name, greeting);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void helloPathTest() throws Exception {
        String name = null;
        String response = api.helloPath(name);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void helloQueryTest() throws Exception {
        String greeting = null;
        String response = api.helloQuery(greeting);

        // TODO: test validations
    }
}
